spring.ai.openai.api-key=unset
spring.ai.openai.base-url=http://localhost:8000
spring.ai.openai.chat.options.model=mlx-community/DeepSeek-OCR-2-bf16
#spring.ai.openai.chat.options.model=mlx-community/PaddleOCR-VL-1.5-bf16
spring.ai.openai.chat.options.temperature=0.1
