##
#spring.ai.embedding.transformer.onnx.modelUri=https://huggingface.co/intfloat/e5-small-v2/resolve/main/model.onnx
#spring.ai.embedding.transformer.onnx.modelOutputName=token_embeddings
##
#spring.ai.embedding.transformer.tokenizer.uri=https://huggingface.co/intfloat/e5-small-v2/raw/main/tokenizer.json
#spring.ai.embedding.transformer.tokenizer.options.padding=true
#
#
#
#
# none to disable
#spring.ai.model.embedding=ollama
##
#spring.ai.ollama.base-url=http://localhost:11434
## HuggingFace Models
#spring.ai.ollama.embedding.options.model=hf.co/mixedbread-ai/mxbai-embed-large-v1
##
#spring.ai.ollama.init.pull-model-strategy=when_missing
#spring.ai.ollama.init.timeout=5m
#spring.ai.ollama.init.max-retries=1
