<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>xyz.kail.github</groupId>
        <artifactId>Spring-AI</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>hello-spring-ai-otel-langfuse</artifactId>

    <dependencies>

        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-starter-model-ollama</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <!-- 传递依赖
         micrometer-registry-otlp
         micrometer-tracing-bridge-otel  Tracing 抽象与 OpenTelemetry 桥接
         opentelemetry-exporter-otlp     Trace 数据推送给 OpenTelemetry Collector
         -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-opentelemetry</artifactId>
        </dependency>

    </dependencies>


</project>