spring.application.name=mcp-calculator
spring.ai.mcp.server.name=My-Java-Calculator
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.stdio=false
# npx @modelcontextprotocol/inspector Debug UI
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp
#
#
#
logging.level.root=INFO