#
# chat
#
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=gemma4:12b-mlx
spring.ai.ollama.init.pull-model-strategy=never
spring.ai.ollama.init.timeout=5m
spring.ai.ollama.init.max-retries=1
#
# embedding
#
spring.ai.model.embedding=ollama
spring.ai.ollama.embedding.model=bge-m3:latest
#
#
#
#spring.ai.vectorstore.observations.log-query-response=true
#
#
#
logging.level.org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor=debug